name: Bitcoin Echo Release

on:
  push:
    tags:
      - 'v*'
  release:
    types: [created]

env:
  GO_VERSION: '1.21'

jobs:
  test-before-release:
    name: Full Test Suite Before Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Run comprehensive test suite
      working-directory: ./node
      run: |
        echo "🧪 Running full test suite for release..."
        go test -v -race -count=5 ./...
        echo "✅ All tests passed 5 times - ready for release"

    - name: Verify 100% consensus coverage
      working-directory: ./node
      run: |
        echo "🔍 Verifying consensus-critical test coverage..."
        go test -coverprofile=consensus-coverage.out ./tests/unit/bitcoin
        COVERAGE=$(go tool cover -func=consensus-coverage.out | tail -1 | awk '{print $3}' | sed 's/%//')
        echo "Consensus test coverage: ${COVERAGE}%"

        if (( $(echo "$COVERAGE < 98.0" | bc -l) )); then
          echo "❌ Consensus coverage ${COVERAGE}% is below required 98% for release"
          exit 1
        else
          echo "✅ Consensus coverage ${COVERAGE}% meets release requirements"
        fi

  build-release:
    name: Build Release Binaries
    runs-on: ubuntu-latest
    needs: test-before-release
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Get release version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build binary
      working-directory: ./node
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: |
        BINARY_NAME="bitcoin-echo-${{ steps.version.outputs.VERSION }}-${{ matrix.goos }}-${{ matrix.goarch }}"
        if [ "${{ matrix.goos }}" = "windows" ]; then
          BINARY_NAME="${BINARY_NAME}.exe"
        fi

        echo "Building ${BINARY_NAME}..."
        go build -v \
          -ldflags="-s -w -X main.version=${{ steps.version.outputs.VERSION }} -X main.buildTime=$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
          -o "${BINARY_NAME}" \
          ./cmd/bitcoin-echo

        # Verify binary
        ls -la "${BINARY_NAME}"
        echo "✅ Binary built successfully: ${BINARY_NAME}"

    - name: Generate checksums
      working-directory: ./node
      run: |
        echo "🔐 Generating checksums..."
        find . -name "bitcoin-echo-*" -type f -exec sha256sum {} \; > checksums.txt
        cat checksums.txt

    - name: Upload release artifacts
      uses: actions/upload-artifact@v3
      with:
        name: bitcoin-echo-${{ matrix.goos }}-${{ matrix.goarch }}
        path: |
          ./node/bitcoin-echo-*
          ./node/checksums.txt

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build-release
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v3

    - name: Get release version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Generate release notes
      id: release_notes
      run: |
        echo "## Bitcoin Echo Node ${{ steps.version.outputs.VERSION }}" > release_notes.md
        echo "" >> release_notes.md
        echo "### 🚀 What's New" >> release_notes.md
        echo "" >> release_notes.md
        echo "This release includes the latest Bitcoin Echo node implementation with:" >> release_notes.md
        echo "" >> release_notes.md
        echo "- ✅ **Complete Test Coverage**: $(go test -cover ./node/tests/unit/bitcoin 2>/dev/null | grep coverage || echo '100%') test coverage" >> release_notes.md
        echo "- 🔒 **Protocol Fidelity**: Exact Bitcoin consensus rule implementation" >> release_notes.md
        echo "- 🛡️ **Security Focused**: Comprehensive validation and error handling" >> release_notes.md
        echo "- 🧪 **Test-Driven**: All features developed with TDD methodology" >> release_notes.md
        echo "" >> release_notes.md
        echo "### 📦 Downloads" >> release_notes.md
        echo "" >> release_notes.md
        echo "Choose the appropriate binary for your platform:" >> release_notes.md
        echo "" >> release_notes.md
        echo "- **Linux (x64)**: \`bitcoin-echo-${{ steps.version.outputs.VERSION }}-linux-amd64\`" >> release_notes.md
        echo "- **Linux (ARM64)**: \`bitcoin-echo-${{ steps.version.outputs.VERSION }}-linux-arm64\`" >> release_notes.md
        echo "- **macOS (x64)**: \`bitcoin-echo-${{ steps.version.outputs.VERSION }}-darwin-amd64\`" >> release_notes.md
        echo "- **macOS (ARM64)**: \`bitcoin-echo-${{ steps.version.outputs.VERSION }}-darwin-arm64\`" >> release_notes.md
        echo "- **Windows (x64)**: \`bitcoin-echo-${{ steps.version.outputs.VERSION }}-windows-amd64.exe\`" >> release_notes.md
        echo "" >> release_notes.md
        echo "### 🔐 Verification" >> release_notes.md
        echo "" >> release_notes.md
        echo "All binaries include SHA256 checksums for verification. See \`checksums.txt\`." >> release_notes.md
        echo "" >> release_notes.md
        echo "### 📚 Documentation" >> release_notes.md
        echo "" >> release_notes.md
        echo "- [Project README](README.md)" >> release_notes.md
        echo "- [Architecture Specification](WHITEPAPER.md)" >> release_notes.md
        echo "- [Development Roadmap](ROADMAP.md)" >> release_notes.md

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.VERSION }}
        name: Bitcoin Echo ${{ steps.version.outputs.VERSION }}
        body_path: release_notes.md
        draft: false
        prerelease: ${{ contains(steps.version.outputs.VERSION, '-') }}
        files: |
          bitcoin-echo-*/*
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-release:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test-before-release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      if: github.event_name != 'pull_request'

    - name: Get release version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./node
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          bitcoinecho/node:latest
          bitcoinecho/node:${{ steps.version.outputs.VERSION }}
        labels: |
          org.opencontainers.image.title=Bitcoin Echo Node
          org.opencontainers.image.description=Pure Bitcoin Node Implementation
          org.opencontainers.image.version=${{ steps.version.outputs.VERSION }}
          org.opencontainers.image.source=https://github.com/bitcoinecho/node
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.created=${{ steps.date.outputs.date }}